#ifndef CYBERDECK_I2S_PINS_H
#define CYBERDECK_I2S_PINS_H

#include <hal/nrf_gpio.h>

#define CYBERDECK_I2S_SCK_PIN   NRF_GPIO_PIN_MAP(1, 9)
#define CYBERDECK_I2S_LRCK_PIN  NRF_GPIO_PIN_MAP(0, 8)
#define CYBERDECK_I2S_MCK_PIN   NRF_GPIO_PIN_MAP(0, 6)
#define CYBERDECK_I2S_SDOUT_PIN NRF_GPIO_PIN_MAP(1, 8)
#define CYBERDECK_I2S_SDIN_PIN  NRF_GPIO_PIN_MAP(0, 7)

#endif
